
tee create_database_LCWEB_PORTFOLIO_and_user_02112025.log

DROP DATABASE IF EXISTS `LCWEB_PORTFOLIO`;

DROP USER IF EXISTS 'LCWEB_FRONTEND01'@'localhost';
DROP USER IF EXISTS 'LCWEB_BACKEND01'@'localhost';


CREATE DATABASE `LCWEB_PORTFOLIO` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;



CREATE USER 'LCWEB_FRONTEND01'@'localhost' IDENTIFIED BY 'dcg_RfvDFv(fg45$fbjt74)';


CREATE USER 'LCWEB_BACKEND01'@'localhost' IDENTIFIED BY 'dcg_Rfv643!fvTb(6369_D';


GRANT SELECT ON LCWEB_PORTFOLIO.* TO 'LCWEB_FRONTEND01'@'localhost';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON LCWEB_PORTFOLIO.* TO 'LCWEB_BACKEND01'@'localhost';
FLUSH PRIVILEGES;


notee;

quit
